### ISSUE TITLE
about the original contribution of this code

### ISSUE THREAD

**Issue by shizi626** [NELSONZHAO/zhihu#35]
I think you just copy [others github code](https://github.com/udacity/deep-learning/blob/master/seq2seq/sequence_to_sequence_implementation.ipynb) and translate it to Chinese.
Please give a reference to the original github.

**Comment by NELSONZHAO** [comment]
Thanks for reminding me. I have already show the reference in my original column essay, but forgot to write in this code file and repo, I will update ASAP. Thank u again.
